<a href="https://colab.research.google.com/github/Ayasa18/DataAnalysisLearning/blob/main/Numpy/NumpyArray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# **Numpy Array**

In [2]:
my_list = [1,2,3]

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# **3Dimension Array**

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(2,2)

array([[0.8604995 , 0.07353821],
       [0.30466038, 0.09996818]])

In [17]:
np.random.randn(2)

array([-0.59184503,  0.38080167])

In [18]:
np.random.randint(8,100,10)

array([52, 48, 23, 32, 69, 48, 51, 44, 86, 80])

# **Example Array Numpy**

In [20]:
arr=np.arange(25)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
ranarr= np.random.randint(0,50,10)

In [23]:
ranarr

array([49, 44, 18,  1, 13,  9,  4, 19, 18, 46])

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
ranarr.max()

49

In [26]:
ranarr.min()

1

# **IndexLocation**

In [27]:
ranarr

array([49, 44, 18,  1, 13,  9,  4, 19, 18, 46])

In [28]:
ranarr.argmax()

0

In [29]:
ranarr.argmin()

3

In [30]:
arr.dtype

dtype('int64')