<a href="https://colab.research.google.com/github/Ayasa18/DataAnalysisLearning/blob/main/Numpy/NumpyIndexingAndSelection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# **NumpyIndexing**

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr[0:5] = 100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr = np.arange(0,11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
slice_of_arr = arr[0:6]

In [14]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [15]:
slice_of_arr[:] = 99

In [16]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [17]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# **Array 2D**

In [18]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [19]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [20]:
arr_2d[0]

array([ 5, 10, 15])

In [21]:
arr_2d[2,1]

40

In [22]:
arr_2d[:2,:1]

array([[ 5],
       [20]])

In [23]:
arr = np.arange(1,11)

In [24]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [26]:
bool_arr = arr>5

In [27]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [28]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [29]:
arr_2d = np.arange(50).reshape(5,10)

In [32]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [31]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [33]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])